const gulp = require('gulp');
const htmlmin = require('gulp-htmlmin');

// 任務：壓縮 HTML + JS + CSS
function buildHTML() {
    return gulp.src('source/**/*.html')
        .pipe(htmlmin({ 
            collapseWhitespace: true,      // 壓縮空白
            removeComments: true,         // 移除註解
            minifyJS: true,               // 強力壓縮內嵌 JS
            minifyCSS: true,              // 強力壓縮內嵌 CSS
            includeAutoGeneratedTags: true,
            processConditionalComments: true,
            removeEmptyAttributes: true,
            removeRedundantAttributes: true
        }))
        .pipe(gulp.dest('./docs/'));
}

// 任務：複製資產
function copyAssets() {
    // 加上 { encoding: false } 確保 PDF 不會毀損
    return gulp.src('source/assets/**/*', { encoding: false })
        .pipe(gulp.dest('./docs/assets/'));
}

// 組合任務
const build = gulp.series(buildHTML, copyAssets);

// 匯出任務
exports.build = build;
exports.default = build;