const gulp = require('gulp');
const htmlmin = require('gulp-htmlmin');

gulp.task('build', async function() {
    // 1. 處理 HTML (暴力壓縮 + JS/CSS 壓縮)
    gulp.src('source/**/*.html')
        .pipe(htmlmin({ 
            collapseWhitespace: true, 
            removeComments: true,
            minifyJS: true, 
            minifyCSS: true,
            ignoreCustomFragments: [ /<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/ ],
            includeAutoGeneratedTags: false // 即使 HTML 不完美也強制處理
        }))
        .pipe(gulp.dest('./docs/'));

    // 2. 處理 Assets (確保圖片、PDF 完全複製到 docs/assets)
    // 這裡增加 { encoding: false } 確保 PDF 不會毀損
    gulp.src('source/assets/**/*', { encoding: false })
        .pipe(gulp.dest('./docs/assets/'));
});